application: isg13-ipnd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /Style
  static_dir: Style

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: template.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest